# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30, null=True)),
                ('hometeamname', models.CharField(max_length=100, null=True)),
                ('matchday', models.PositiveIntegerField(null=True)),
                ('hometeamid', models.PositiveIntegerField(null=True)),
                ('goalsawayteam', models.PositiveIntegerField(null=True)),
                ('goalshometeam', models.PositiveIntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('competitionid', models.PositiveIntegerField(null=True)),
                ('awayteamname', models.CharField(max_length=100, null=True)),
                ('halftimegoalsawayteam', models.PositiveIntegerField(null=True)),
                ('halftimegoalshometeam', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
