# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=30)),
                ('league', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
