# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('shortname', models.CharField(max_length=30, null=True)),
                ('cresturl', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
