# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='cresturl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
