# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171027_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('matchday', models.PositiveIntegerField()),
                ('homeTeamId', models.PositiveIntegerField()),
                ('goalsAwayTeam', models.PositiveIntegerField()),
                ('goalsHomeTeam', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('competitionId', models.PositiveIntegerField()),
                ('homeTeamName', models.CharField(max_length=100)),
            ],
        ),
    ]
