# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='awayTeamName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
