# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171030_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='awayteamid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
