# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fixtures_awayteamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='awayteamname',
        ),
        migrations.RemoveField(
            model_name='fixtures',
            name='hometeamname',
        ),
    ]
