# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fixtures_awayteamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='competitionId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='goalsAwayTeam',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='goalsHomeTeam',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='homeTeamId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='homeTeamName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='matchday',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
