# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20171030_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('hometeam', models.CharField(max_length=100, null=True)),
                ('awayteam', models.CharField(max_length=100, null=True)),
                ('home', models.FloatField(null=True)),
                ('draw', models.FloatField(null=True)),
                ('away', models.FloatField(null=True)),
            ],
        ),
    ]
