# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20171027_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtures',
            old_name='awayTeamName',
            new_name='awayteamname',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='competitionId',
            new_name='competitionid',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='goalsAwayTeam',
            new_name='goalsawayteam',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='goalsHomeTeam',
            new_name='goalshometeam',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='homeTeamId',
            new_name='hometeamid',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='homeTeamName',
            new_name='hometeamname',
        ),
    ]
