# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20171027_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='halftimegoalsawayteam',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='halftimegoalshometeam',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
