# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
