# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_teams_oddsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='oddsurl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
