# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_competitions_oddsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='league',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
