# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20171030_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='oddsaway',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='oddsdraw',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='oddshome',
            field=models.FloatField(null=True),
        ),
    ]
