# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20171030_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accastats',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(null=True)),
                ('competition', models.PositiveIntegerField(null=True)),
                ('home', models.CharField(max_length=30, null=True)),
                ('away', models.CharField(max_length=30, null=True)),
                ('market', models.PositiveIntegerField(null=True)),
                ('bettype', models.PositiveIntegerField(null=True)),
                ('pred', models.PositiveIntegerField(null=True)),
                ('odd', models.FloatField(null=True)),
            ],
        ),
    ]
