# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_accastats'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='accastats_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
