# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_competitions_accastats_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='accastats_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
