---
# tasks file for push
    
- name : add files
  command: bash -lc "cd .. && git add ."

- name : commit
  command: bash -lc "cd .. && git commit -m '{{comment}}'"

- name : push
  command: bash -lc "git push https://'{{git_username}}':'{{git_pwd}}'@{{repo}}"
