---
# tasks file for push
- block :
  - name : add files
    command: bash -lc "cd .. && git add ."

  - name : commit
    command: bash -lc "cd .. && git commit -m '{{comment}}'"

  - name : push
    command: bash -lc "git push https://'{{git_username}}':'{{git_pwd}}'@{{repo}}"
  tags :
    - push
    - deploy
