- name : push on github
  hosts : localhost
  connection : local
  vars_files :
    - vars.yml
  tasks :
    - name : check ssh-pass package
      package :
        name : sshpass
        state : present
    - name : add files
      command: bash -lc "cd .. && git add ."
    - name : commit
      command: bash -lc "cd .. && git commit -m '{{comment}}'"
    - name : push
      command: bash -lc "git push https://'{{git_username}}':'{{git_pwd}}'@{{repo}}"

- name : deploy project
  hosts : all
  vars_files :
    - vars.yml
  tasks :
    - name : remove old docker packages
      package :
        name : "{{item}}"
        state : absent
      with_items :
        - docker
        - docker-engine
        - docker.io
    - docker_service:
        project_src: /root/projects/django-postgresql
        state: absent
    - git:
        repo: "https://{{repo}}"
        dest: "{{dest}}"
