- name : push on github
  hosts : localhost
  connection : local
  vars_files :
    - vars.yml
  tasks :
    - name : git add files
      command: bash -lc "cd .. && git add ."
    - name : git commit
      command: bash -lc "cd .. && git commit -m 'test'"

- name : deploy project
  hosts : all
  vars_files :
    - vars.yml
  tasks :
    - docker_service:
        project_src: /root/projects/django-postgresql
        state: absent
    - git:
        repo: "{{repo}}"
        dest: /itl
    - debug:
        msg : "{{git_username}} , {{git_pwd}}"
